from typing import Optional, AsyncGenerator, Any

from google.adk import Runner
from google.adk.agents import RunConfig, InvocationContext
from google.adk.events import Event
from google.adk.sessions import Session
from google.adk.telemetry import tracer
from google.genai import types


class SessionDirectRunner(Runner):
    async def run_async(
            self,
            *,
            user_id: str,
            session: Session,
            new_message: types.Content,
            state_delta: Optional[dict[str, Any]] = None,
            run_config: RunConfig = RunConfig(),
    ) -> AsyncGenerator[Event, None]:
        """Main entry method to run the agent in this runner.

        Args:
          user_id: The user ID of the session.
          session_id: The session ID of the session.
          new_message: A new message to append to the session.
          run_config: The run config for the agent.

        Yields:
          The events generated by the agent.
        """
        with tracer.start_as_current_span('invocation'):
            if not session:
                raise ValueError(f'Session not found')

            invocation_context = self._new_invocation_context(
                session,
                new_message=new_message,
                run_config=run_config,
            )
            root_agent = self.agent

            # Modify user message before execution.
            modified_user_message = (
                await invocation_context.plugin_manager.run_on_user_message_callback(
                    invocation_context=invocation_context, user_message=new_message
                )
            )
            if modified_user_message is not None:
                new_message = modified_user_message

            if new_message:
                await self._append_new_message_to_session(
                    session=session,
                    new_message=new_message,
                    invocation_context=invocation_context,
                    save_input_blobs_as_artifacts=run_config.save_input_blobs_as_artifacts,
                    state_delta=state_delta,
                )

            invocation_context.agent = self._find_agent_to_run(session, root_agent)

            async def execute(ctx: InvocationContext) -> AsyncGenerator[Event]:
                async for event in ctx.agent.run_async(ctx):
                    yield event

            async for event in self._exec_with_plugin(
                    invocation_context, session, execute
            ):
                yield event
