services:
  devops-agent:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 10009:10009
    env_file: .env

  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - 6006:6006